version: "2"

plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR12"
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
      rulesets: "unusedcode,codesize"
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-11"
    extensions:
      - .js
      - .vue
  csslint:
    enabled: true
exclude_patterns:
  - bootstrap
  - database
  - laradock
  - node_modules
  - public
  - routes
  - scripts
  - storage
  - tests
  - vendor
